version: "3.8"
services:
  postgres:
    restart: always
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
       - "127.0.0.1:5432:5432"
